name: JServer
version: 1.0.0
author: jsbrn
main: main.JServer
api-version: 1.13
commands:
  mark:
    description: Add a marker to the map.
    usage: /mark <name> <icon>
  unmark:
    description: Remove a marker from the map.
    usage: /unmark <name>