name: OpenMC
version: 0.0.1
author: jsbrn
main: main.OpenMC
api-version: 1.13
commands:
  guide:
    description: Lost the guide? Get a new one!
    usage: /guide
  plots:
    description: List all your plots.
    usage: /plots
  deposit:
    description: Deposit emeralds from your inventory into account.
    usage: /deposit <amount>
  withdraw:
    description: Withdraw emeralds from your account.
    usage: /withdraw <amount>
  stats:
    description: Toggle the stats display (sidebar).
    usage: /stats
  set:
    description: Admin command. Sets a value for the specified player.
    usage: /set (time|rep) <player> <amount>
  add:
    description: Admin command. Adds a value to the specified player.
    usage: /add time <player> <amount>