name: OpenMC
version: 0.0.1
author: jsbrn
main: main.OpenMC
api-version: 1.13
commands:
  guide:
    description: Lost the guide? Get a new one!
    usage: /guide
  plot:
    description: Admin command. Remove (or change ownership of) plots.
    usage: /plot (delete|setOwner) [ownerUUID]
  set:
    description: Admin command. Sets a value for the specified player.
    usage: /set (time|rep) <player> <amount>
  invite:
    description: Invite a friend to join your group.
    usage: /invite <player>
  accept:
    description: Accept a friend's group invitation.
    usage: /accept <player>
  leave:
    description: Leave your current group.
    usage: /leave